---
title: "smNRPS-HMP2IBD-analysis"
author: "Francine Camacho"
date: "8/30/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE}
#load necessary packages 
library(tidyverse)
library(ggsci)
library(psych)
library(reshape2)
library(ggpubr)

```

We must filter our BLASTn quantification results by BGC coverage criteria (>=50).

```{r}
#load quantifier data 
quantifier_df <- read_delim("combined-HMP2-IBD-metagenomes-quantifier-results.txt", col_names = F, delim = "\t")
names(quantifier_df) <- c("bgcName", "Coverage", "RPKM", "Sample") # add column names

filter_quantifier_df <- quantifier_df %>% filter(Coverage >= 50)  # filter by coverage 

sample_metadata<-read_csv("hmp2_project_metadata_2016-10-15.csv", col_names = TRUE) %>% select(., `External ID`, `Participant ID`,`data_type`, diagnosis )
colnames(sample_metadata)<- c("ExternalID", "ParticipantID", "data_type","GroupAttribute")
sample_metadata_metagenomes <- sample_metadata %>% filter(data_type == "metagenomics") 

#add sample metadata to filtered quantifier dataframe 
filter_quantifier_df <- filter_quantifier_df %>% inner_join(., sample_metadata_metagenomes, by = c("Sample"="ExternalID"))
# retrieve BGC class from bgcName 
dna_results_df <- filter_quantifier_df %>% separate(., bgcName,c("sampleID", "scaffoldName", "clusterlen", "bgcClass", "software", "Coord"),sep = "__", remove = F) %>% select(-c(2:4,6:7))

############################
#Group BGC Class for figure 
recode_bgcClass<-function(df){
  PKS <- c("t2pks","transatpks","t1pks","lantipeptide-t2pks","otherks","otherks-transatpks", "otherks-t1pks")
  NRPS <- c("nrps","nrps-bacteriocin","nrps-ladderane","ladderane-nrps","nrps-lantipeptide","arylpolyene-nrps")
  Terpene <- "terpene"
  hybrid_pks_nrps<- c("nrps-t1pks","transatpks-otherks-nrps")
  Others <- c("arylpolyene","other", "resorcinol","butyrolactone", "ladderane", "siderophore", "hserlactone", "bacteriocin-arylpolyene","amglyccycl","ladderane-arylpolyene","phenazine")
  RiPPs <- c("microcin","bacteriocin","lantipeptide","lassopeptide","bacteriocin-lantipeptide","sactipeptide", "thiopeptide","bacteriocin-proteusin", "glycocin","microcin-lassopeptide","proteusin-bacteriocin")
  
  df$bgcClass[df$bgcClass %in% PKS ==TRUE] <- "PKS"
  df$bgcClass[df$bgcClass %in% NRPS ==TRUE] <- "NRPS"
  df$bgcClass[df$bgcClass == Terpene] <- "Terpene"
  df$bgcClass[df$bgcClass %in% hybrid_pks_nrps ==TRUE] <- "Hybrid PKS-NRPS"
  df$bgcClass[df$bgcClass %in% Others ==TRUE] <- "Others"
  df$bgcClass[df$bgcClass %in% RiPPs ==TRUE] <- "RiPPs"
  return(df)
  
}

hmp2_metagenomes_filtered_results<-recode_bgcClass(dna_results_df)

#knitr::kable(hmp2_metagenomes_filtered_results, digits = 2, caption = "BGC class counts identified using antiSMASH in  HMP2-metagenomes cohort.")
#############################

#############################
#cultured bacteria vs uncultivated bacteria pie chart
species_df <- read_csv("species-profiler-results/species_results-HMP2-IBD_UniProt.csv", col_names = T)
species_df[is.na(species_df)]<-"N/A"
species_df$PHYLUM <- ifelse(species_df$PHYLUM == "N/A", species_df$Manual_PHYLUM, species_df$PHYLUM)
species_df$ORGANISM <- ifelse(species_df$ORGANISM == "N/A", species_df$Manual_ORGANISM, species_df$ORGANISM)

species_df$PHYLUM[species_df$PHYLUM == "N/A" ] <-"Unassigned"

species_df_bgc_class <-species_df %>% separate(., BGC_NAME,c("sampleID", "scaffoldName", "clusterlen", "bgcClass", "software", "Coord"),sep = "__", remove = F) %>% select(-c(2:4,6:7))
species_recoded_bgc_results<-recode_bgcClass(species_df_bgc_class)

species_recoded_bgc_results %>% group_by(PHYLUM,bgcClass) %>% count() %>% ggplot(.,aes(reorder(PHYLUM, n), n)) + geom_col(aes(fill = bgcClass)) + scale_fill_npg() + coord_flip()+ theme_bw() 
ggsave("BGC-counts-perclass_Phyla-barplot.eps", width = 7.3, height = 6.31, units = "in", device = "eps") 
species_recoded_bgc_results %>% group_by(PHYLUM) %>% count() %>% ggplot(.,aes(reorder(PHYLUM, n), n)) + geom_col() + scale_fill_npg() + coord_flip()+ theme_bw() + xlab("Phyla") + ylab("Total BGCs detected") +geom_text(aes(label=n), vjust=0,hjust=-.5)
ggsave("BGC-counts-perPhyla-barplot.eps", width =11, height = 6.31, units = "in", device = "eps") 
```

Summary statistics for filtered data per cohort. 

```{r}
### calculate hit ratio for each BGC within each cohort 
calculate_hitRatio <-function(data, metadata){
  metadata_counts<- metadata %>% group_by(GroupAttribute) %>% count() %>% ungroup()
  bgc_counts <- data %>% group_by(bgcName,GroupAttribute) %>% count() %>% ungroup()
  hitRatio_df <- data.frame() # intialize results df 
  for (i in 1:nrow(metadata_counts)){
    diseaseStatus <- metadata_counts[i,]$GroupAttribute
    diseaseStatus_count <- metadata_counts[i,]$n
    disease_hitratio <- bgc_counts %>% filter(GroupAttribute == diseaseStatus) %>%  mutate(., hitRatio = case_when(GroupAttribute == diseaseStatus ~ (n/diseaseStatus_count)*100))
    hitRatio_df<-rbind(hitRatio_df,disease_hitratio)
    
  }
  return(hitRatio_df)
}
calculate_hitRatio_byPart <-function(data, metadata){
  metadata_counts<- metadata %>% group_by(ParticipantID,GroupAttribute) %>% count() %>% ungroup() %>% group_by(GroupAttribute) %>% count() %>% ungroup()
  bgc_counts <- data %>% group_by(bgcName,GroupAttribute,ParticipantID) %>% count() %>% ungroup() %>% group_by(bgcName,GroupAttribute) %>% count() %>% ungroup()
  hitRatio_df <- data.frame() # intialize results df 
  for (i in 1:nrow(metadata_counts)){
    diseaseStatus <- metadata_counts[i,]$GroupAttribute
    diseaseStatus_count <- metadata_counts[i,]$nn
    disease_hitratio <- bgc_counts %>% filter(GroupAttribute == diseaseStatus) %>%  mutate(., hitRatio = case_when(GroupAttribute == diseaseStatus ~ (nn/diseaseStatus_count)*100))
    hitRatio_df<-rbind(hitRatio_df,disease_hitratio)
    
  }
  return(hitRatio_df)
}
#hitratio by samples and not participant 
hmp2_metagenome_hitratio <- calculate_hitRatio(hmp2_metagenomes_filtered_results, sample_metadata_metagenomes)
hmp2_metagenome_hitratiobyPart <- calculate_hitRatio_byPart(hmp2_metagenomes_filtered_results, sample_metadata_metagenomes)

################################################

bar_plot_per_cluster<- function(df, cluster){
  plot_title <- paste0(cluster, "-","barplot",".eps")
  df %>% filter(bgcName == cluster) %>% group_by(GroupAttribute) %>% mutate(ymean= mean(RPKM)) %>% mutate(ymedian= median(RPKM)) %>%  ggplot(., aes(Sample,RPKM)) + geom_col()+geom_hline(aes(yintercept=ymedian), color="red", linetype="dashed")+geom_hline(aes(yintercept=ymean), color="red", linetype="solid")+theme_pubclean()+ facet_grid(~GroupAttribute, switch= "x",scales = "free_x", space = "free_x") + xlab("Disease")+  theme(
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) + ggtitle(cluster) + theme(plot.title = element_text(hjust = 0.5,face = "bold",size = "24"))
  
   ggsave(plot_title, width = 11, height = 5, units = "in", device = "eps") 

}




################################################
#smNRPS-CB:C3008__NODE_58_length_80320_cov_9.89467__38512__nrps__ANTISMASH__41808_80320 
#by samples
hmp2_metagenome_hitratio %>% filter(bgcName == "C3008__NODE_58_length_80320_cov_9.89467__38512__nrps__ANTISMASH__41808_80320")
#by participants:
hmp2_metagenome_hitratiobyPart %>% filter(bgcName == "C3008__NODE_58_length_80320_cov_9.89467__38512__nrps__ANTISMASH__41808_80320")
#smNRPS-CC:C4004__NODE_591_length_10305_cov_3.58927__10305__nrps__ANTISMASH__0_10305  
#######################
hmp2_metagenome_hitratio %>% filter(bgcName == "C4004__NODE_591_length_10305_cov_3.58927__10305__nrps__ANTISMASH__0_10305")
hmp2_metagenome_hitratiobyPart %>% filter(bgcName == "C4004__NODE_591_length_10305_cov_3.58927__10305__nrps__ANTISMASH__0_10305")
#######################
suppressWarnings(describeBy(hmp2_metagenome_hitratio, hmp2_metagenome_hitratio$GroupAttribute)) # #Stats for Hit Ratio
suppressWarnings(describeBy(hmp2_metagenomes_filtered_results, hmp2_metagenomes_filtered_results$GroupAttribute)) # Stats for RPKM 
#######################
#for Total BGCs in each sample
# Try to order facets.
reorder_within <- function(x, by, within, fun = mean, sep = "___", ...) {
  new_x <- paste(x, within, sep = sep)
  stats::reorder(new_x, by, FUN = fun)
}


scale_x_reordered <- function(..., sep = "___") {
  reg <- paste0(sep, ".+$")
  ggplot2::scale_x_discrete(labels = function(x) gsub(reg, "", x), ...)
}


scale_y_reordered <- function(..., sep = "___") {
  reg <- paste0(sep, ".+$")
  ggplot2::scale_y_discrete(labels = function(x) gsub(reg, "", x), ...)
}
######## 
#figure for BGC cclass total molecules detected in each samples in each cohort # remove other group
hmp2_metagenomes_filtered_results %>% filter(GroupAttribute!= "Other") %>% group_by(GroupAttribute,bgcClass) %>% count(Sample) %>% ggplot(.,aes(reorder_within(Sample, n, GroupAttribute), n)) + geom_col(aes(fill = bgcClass)) + scale_fill_npg()+ facet_grid(~GroupAttribute, switch = "x", scales = "free_x", space = "free_x") + scale_x_reordered()+
    theme(panel.spacing = unit(0, "lines"), 
         strip.background = element_blank()) + xlab("Disease Status")+ ylab("Total BGCs detected") + theme_bw() + theme(axis.text.x = element_blank(),axis.ticks.x = element_blank())
ggsave("HMP-2-IBD_bgc-counts-per-sample.eps", width = 7.3, height = 6.31, units = "in", device = "eps") 

#########

wilcoxon_test<-function(df, cohort, testType){
  df$GroupAttribute <-as.factor(df$GroupAttribute)
  print(levels(df$GroupAttribute))
  results<-df  %>% group_by(GroupAttribute) %>% count(Sample) %>% wilcox.test(n ~ GroupAttribute, data=., paired=F, alternative = testType,subset = GroupAttribute %in% cohort )
  print(results)
}

#levels = "C"  "CD" "UC"
wilcoxon_test(hmp2_metagenomes_filtered_results, c("Healthy control","Crohn's Disease"), "greater") # 0.9973
wilcoxon_test(hmp2_metagenomes_filtered_results, c("Crohn's Disease","Ulcerative colitis"), "less") #0.8059
wilcoxon_test(hmp2_metagenomes_filtered_results, c("Healthy control","Ulcerative colitis"), "greater")#0.004894
```

```{r}
hmp2_metagenomes_filtered_results %>% filter(GroupAttribute == "Healthy control" | GroupAttribute == "Crohn's Disease") %>% group_by(GroupAttribute) %>% count(Sample)%>% ggplot(., aes(GroupAttribute, n, color = GroupAttribute)) + geom_boxplot(outlier.colour = NA) +  geom_jitter(width = 0.2)+stat_summary(fun.y = mean, geom = "errorbar", aes(ymax = ..y.., ymin = ..y..), width = .75, linetype = "dashed")+scale_color_npg()+ theme_classic() 

hmp2_metagenomes_filtered_results %>% filter(GroupAttribute == "Ulcerative colitis" | GroupAttribute == "Crohn's Disease") %>% group_by(GroupAttribute) %>% count(Sample)%>% ggplot(., aes(GroupAttribute, n, color = GroupAttribute)) + geom_boxplot(outlier.colour = NA) +  geom_jitter(width = 0.2)+stat_summary(fun.y = mean, geom = "errorbar", aes(ymax = ..y.., ymin = ..y..), width = .75, linetype = "dashed")+scale_color_npg()+ theme_classic()  

hmp2_metagenomes_filtered_results %>% filter(GroupAttribute == "Ulcerative colitis" | GroupAttribute == "Healthy control") %>% group_by(GroupAttribute) %>% count(Sample)%>% ggplot(., aes(GroupAttribute, n, color = GroupAttribute)) + geom_boxplot(outlier.colour = NA) +  geom_jitter(width = 0.2)+stat_summary(fun.y = mean, geom = "errorbar", aes(ymax = ..y.., ymin = ..y..), width = .75, linetype = "dashed")+scale_color_npg()+ theme_classic() 
```

Analysis for Crohns vs Controls: iterative KW test; LDA analysis; Random forest 

```{r}
# Function to add BGCs that zeros when a BGC was not found in a Sample 
prepare_data<-function(df, metadata_df){
  data_wide <- dcast(df, bgcName ~ Sample, value.var="RPKM") 
  data_wide[is.na(data_wide)] <- 0 
  data_melt <- melt(data_wide) %>%  mutate_if(is.factor, as.character) %>% inner_join(.,metadata_df, by = c("variable"="ExternalID") )
  names(data_melt)[2]<-"Sample"
  names(data_melt)[3]<-"RPKM"
  return(data_melt)
  
}

dna_filter_quantifier_df <- prepare_data(hmp2_metagenomes_filtered_results, sample_metadata_metagenomes) 
dna_quantifier_CD_C <-dna_filter_quantifier_df %>% filter(GroupAttribute == "Crohn's Disease" | GroupAttribute == "Healthy control") 
dna_quantifier_UC_C <-dna_filter_quantifier_df %>% filter(GroupAttribute == "Ulcerative colitis" | GroupAttribute == "Healthy control") 
dna_quantifier_UC_CD <-dna_filter_quantifier_df %>% filter(GroupAttribute == "Ulcerative colitis" | GroupAttribute == "Crohn's Disease") 

################
#Rainin not exact clusters barplot
bar_plot_per_cluster(dna_filter_quantifier_df, "C3008__NODE_58_length_80320_cov_9.89467__38512__nrps__ANTISMASH__41808_80320" ) #smNRPS CB 
bar_plot_per_cluster(dna_filter_quantifier_df, "C4004__NODE_591_length_10305_cov_3.58927__10305__nrps__ANTISMASH__0_10305" ) #smNRPS CC 
#################

#Format dataframe to run lefse 
source("/Users/francinecamacho/Documents/Donia_analysis/smNRPS-manuscript/smNRPS-Crohns/data/format_data_for_lefse.R")

dna_quantifier_CD_C_lefse<-format_data_for_lefse(dna_quantifier_CD_C)
dna_quantifier_UC_C_lefse<-format_data_for_lefse(dna_quantifier_UC_C)
dna_quantifier_UC_CD_lefse<-format_data_for_lefse(dna_quantifier_UC_CD)

#write_delim(dna_quantifier_CD_C_lefse, "HMP2-metagenome-quantifier-results-CD_C-spanish-for-lefse.txt",delim="\t")
#write_delim(dna_quantifier_UC_C_lefse, "HMP2-metagenome-quantifier-results-UC_C-spanish-for-lefse.txt",delim="\t")
#write_delim(dna_quantifier_UC_CD_lefse,"HMP2-metagenome-quantifier-results-UC_CD-spanish-for-lefse.txt",delim="\t")
```


```{r}
# Analysis with pvalue <= .01; LDA Score >2 
########################################################
lefse_CD_C <- read_delim("LEfSe-results/LDA_Effect_Size_CD_C_stricter_pvalue.txt",col_names = F, delim = "\t")
colnames(lefse_CD_C)<-c("BGC", "log(HighestMean_AllClasses)","class_discriminitive","LDA_score", "pvalue")

lefse_CD_C_discriminative_features <- lefse_CD_C %>% filter(!is.na(class_discriminitive) & !is.na(LDA_score))


lefse_CD_C_discriminative_features<-lefse_CD_C_discriminative_features %>% mutate(LDA_score = ifelse(class_discriminitive == "Healthy control", -abs(LDA_score), LDA_score))
                                    
lefse_CD_C_discriminative_features %>%  mutate(BGC = reorder(BGC, LDA_score)) %>%
  ggplot(aes(BGC, LDA_score, fill = class_discriminitive)) +
  geom_bar(stat = "identity")  +
  ylab("LDA SCORE (log 10)") +
  coord_flip() + theme_bw() + scale_fill_manual(values = c("#DC0000FF", "#00A087FF")) + theme(legend.position="top") +theme(legend.title=element_blank())
 ggsave("lefse_CD_C_discriminative_features.eps", width = 10, height = 15, units = "in", device = "eps") 

########################################################
 
lefse_UC_C <- read_delim("LEfSe-results/LDA_Effect_Size_UC_C_stricter_pvalue.txt",col_names = F, delim = "\t")
colnames(lefse_UC_C)<-c("BGC", "log(HighestMean_AllClasses)","class_discriminitive","LDA_score", "pvalue")

lefse_UC_C_discriminative_features <- lefse_UC_C %>% filter(!is.na(class_discriminitive) & !is.na(LDA_score))


lefse_UC_C_discriminative_features<-lefse_UC_C_discriminative_features %>% mutate(LDA_score = ifelse(class_discriminitive == "Healthy control", -abs(LDA_score), LDA_score))
                                    
lefse_UC_C_discriminative_features %>%  mutate(BGC = reorder(BGC, LDA_score)) %>%
  ggplot(aes(BGC, LDA_score, fill = class_discriminitive)) +
  geom_bar(stat = "identity")  +
  ylab("LDA SCORE (log 10)") +
  coord_flip() + theme_bw() + scale_fill_manual(values = c("#DC0000FF", "#00A087FF")) + theme(legend.position="top") +theme(legend.title=element_blank())
ggsave("lefse_UC_C_discriminative_features.eps", width = 10, height = 15, units = "in", device = "eps") 



########################################################
lefse_UC_CD <- read_delim("LEfSe-results/LDA_Effect_Size_UC_CD_stricter_pvalue.txt",col_names = F, delim = "\t")
colnames(lefse_UC_CD)<-c("BGC", "log(HighestMean_AllClasses)","class_discriminitive","LDA_score", "pvalue")

lefse_UC_CD_discriminative_features <- lefse_UC_CD %>% filter(!is.na(class_discriminitive) & !is.na(LDA_score))


lefse_UC_CD_discriminative_features<-lefse_UC_CD_discriminative_features %>% mutate(LDA_score = ifelse(class_discriminitive == "Crohn's Disease", -abs(LDA_score), LDA_score))
                                    
lefse_UC_CD_discriminative_features %>%  mutate(BGC = reorder(BGC, LDA_score)) %>%
  ggplot(aes(BGC, LDA_score, fill = class_discriminitive)) +
  geom_bar(stat = "identity")  +
  ylab("LDA SCORE (log 10)") +
  coord_flip() + theme_bw() + scale_fill_manual(values = c("#DC0000FF", "#00A087FF")) + theme(legend.position="top") +theme(legend.title=element_blank())
ggsave("lefse_UC_CD_discriminative_features.eps", width = 10, height = 15, units = "in", device = "eps") 

```

```{r}
#Venn diagram 
# 
# lefse_CD_C_discriminative_features
# lefse_UC_C_discriminative_features
# lefse_UC_CD_discriminative_features
# 
# enrichedCD_UC_list<-lefse_UC_CD_discriminative_features%>% filter(class_discriminitive == "Crohn's Disease")
# enrichedCD_C_list<-lefse_CD_C_discriminative_features%>% filter(class_discriminitive == "Crohn's Disease")
# gplots::venn(list(enrichedCD_UC = enrichedCD_UC_list$BGC, enrichedCD_C= enrichedCD_C_list$BGC))
```

```{r}
#iterative KW similarly to Lefse to retreive p-values for all BGCs and compare to Lefse results 
#normalized by LEfse methods 
iterativeKW<-function(df, features){
  df<- df %>% group_by(Sample) %>% mutate(sumRPKM = sum(RPKM)) %>% mutate(normalizedRPKM = (RPKM/sumRPKM) * 1000000)
  df$GroupAttribute <-as.factor(df$GroupAttribute)
  features_pvalues<-list()
  pvalues<-list()
  i <-1
  for (i in 1:length(features)){
    featureDF<- df %>% filter(bgcName == features[i]) # current feature data 
    kwResult<-kruskal.test(normalizedRPKM ~ GroupAttribute, data = featureDF)
    features_pvalues <- append(features_pvalues, list(features[i]))
    pvalues<-append(pvalues, list(kwResult$p.value))

    i<-i+1
  }
  resultsDF<-do.call(rbind, Map(data.frame, A=features_pvalues, B=pvalues))
  names(resultsDF) <- c("features", "pvalues")
  #resultsDF$BH.adjusted <- p.adjust(resultsDF$pvalues, method="BH", n = length(resultsDF$pvalues)) # adjust pvalues 
  return(resultsDF)
  
}

####################################
dna_quantifier_CD_C_KW <- iterativeKW(dna_quantifier_CD_C,unique(dna_quantifier_CD_C$bgcName)) 
dna_quantifier_CD_C_KW$pvalues[dna_quantifier_CD_C_KW$pvalues == "NaN"]<- "-"

###################################
dna_quantifier_UC_C_KW <- iterativeKW(dna_quantifier_UC_C,unique(dna_quantifier_UC_C$bgcName)) 
dna_quantifier_UC_C_KW$pvalues[dna_quantifier_UC_C_KW$pvalues == "NaN"]<- "-"

###################################
dna_quantifier_UC_CD_KW <- iterativeKW(dna_quantifier_UC_CD,unique(dna_quantifier_UC_CD$bgcName)) 
dna_quantifier_UC_CD_KW$pvalues[dna_quantifier_UC_CD_KW$pvalues == "NaN"]<- "-"

###################################
supplementary_tables<-function(df, kw_df,taxa_df){
  
  new_df <- df %>% separate(., BGC, into=c("Sample","ScaffoldName", "bgcLen", "bgcClass", "Software","Coords" ), sep = "__")
  recode_df<- new_df %>% mutate(Sample = str_replace_all(Sample, "_", ".")) %>% mutate(ScaffoldName=stringi::stri_replace_last_fixed(ScaffoldName, '_', '.')) %>% mutate(bgcClass=str_replace_all(bgcClass, '_', '-'))%>%unite(., "BGC",c("Sample","ScaffoldName",  "bgcLen", "bgcClass", "Software","Coords" ), sep = "__")
  recode_df[is.na(recode_df)]<-"-"
  
  supp_table<-recode_df%>% inner_join(.,kw_df, by= c("BGC" = "features"))%>% inner_join(.,taxa_df, by = c("BGC"="BGC_NAME")) %>% select(., 1:6,8,11:12)
  names(supp_table)[5]<-"LEfSe_pvalue"
  names(supp_table)[6]<-"manual_pvalue"
  names(supp_table)[7]<-"NCBI refrence sequence acession number"
  names(supp_table)[8]<-"Taxa Name"
  names(supp_table)[9]<-"Phylum"
  return(supp_table)
  }

lefse_CD_C_supp_table<-supplementary_tables(lefse_CD_C,dna_quantifier_CD_C_KW,species_df)

#write_csv(lefse_CD_C_supp_table, "lefse_CD_C_supp_table_1.csv", col_names = T)
lefse_UC_C_supp_table<-supplementary_tables(lefse_UC_C,dna_quantifier_UC_C_KW,species_df)
#write_csv(lefse_UC_C_supp_table, "lefse_UC_C_supp_table_2.csv", col_names = T)
lefse_UC_CD_supp_table<-supplementary_tables(lefse_UC_CD,dna_quantifier_UC_CD_KW,species_df)
#write_csv(lefse_UC_CD_supp_table, "lefse_UC_CD_supp_table_3.csv", col_names = T)
```
